language: ruby
rvm:
  - 2.1.4
  - 2.1.0
addons:
  postgresql: "9.3"
before_script:
  - cp config/database.travis.yml config/database.yml
  - RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
script:
  - bundle exec rspec spec/
