language: ruby
cache:
  directories:
  - vendor/bundle
rvm:
- 2.1.4
addons:
  postgresql: '9.3'
before_script:
- cp config/database.travis.yml config/database.yml
- RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
script:
- bundle exec rspec spec/
after_success:
- mkdir -p .travis
- openssl aes-256-cbc -K $encrypted_ebbfec5e58e4_key -iv $encrypted_ebbfec5e58e4_iv -in dokku.gz.enc -out .travis/dokku.gz -d
- gunzip .travis/dokku.gz
- chmod 600 .travis/dokku*
- eval `ssh-agent -s`
- ssh-add .travis/dokku
- cat .travis/host_key >> ~/.ssh/known_hosts
- git remote add dokku dokku@dokku.codez.it:development_bootcamp
- 'if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then git push dokku master; fi'
notifications:
  slack:
    secure: KbFf1e6G6k1Z4mGNkOm+jmyciCF1yjtQbjgEkEroSMuwM++SGq8yoQHurWVbItbofB+vyA7owCrCSUrIYEpQSSLqoo8EcrHIykif+sWXKzJCpjEE/WseP6nzKMXovYRzUTWMLzv5axtLHwAxy169xkP+vMbAKt/lSNVKrkJB6G0=
