language: ruby
rvm:
- 2.1.4
- 2.1.0
cache: bundler
addons:
  postgresql: '9.3'
before_script:
- cp config/database.travis.yml config/database.yml
- RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
script:
- bundle exec rspec spec/
before_install:
- openssl aes-256-cbc -K $encrypted_ebbfec5e58e4_key -iv $encrypted_ebbfec5e58e4_iv
  -in dokku.pub.enc -out .travis/dokku.pub -d
- openssl aes-256-cbc -K $encrypted_ebbfec5e58e4_key -iv $encrypted_ebbfec5e58e4_iv
  -in dokku.enc -out .travis/dokku -d
after_success:
  - chmod 600 .travis/dokku*
  - ssh-add .travis/dokku
  - git remote add dokku dokku@dokku.codez.it:development_bootcamp
  - git push dokku master
