language: ruby
rvm:
- 2.1.4
- 2.1.0
cache: bundler
addons:
  postgresql: '9.3'
before_script:
- cp config/database.travis.yml config/database.yml
- RAILS_ENV=test bundle exec rake db:drop db:create db:migrate
script:
- bundle exec rspec spec/
after_success:
- openssl aes-256-cbc -K $encrypted_ebbfec5e58e4_key -iv $encrypted_ebbfec5e58e4_iv
  -in dokku.pub.gz.enc -out .travis/dokku.pub.gz -d
- openssl aes-256-cbc -K $encrypted_ebbfec5e58e4_key -iv $encrypted_ebbfec5e58e4_iv
  -in dokku.gz.enc -out .travis/dokku.gz -d
- gunzip .travis/dokku.pub.gz
- gunzip .travis/dokku.gz
- chmod 600 .travis/dokku*
- ssh-add .travis/dokku
- openssl aes-256-cbc -K $encrypted_ebbfec5e58e4_key -iv $encrypted_ebbfec5e58e4_iv
  -in host_key.enc -out .travis/host_key -d
- cat .travis/host_key >> ~/.ssh/known_hosts
- git remote add dokku dokku@dokku.codez.it:development_bootcamp
- git push dokku master
