# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a0de5b5f52fb399b66dccb3887e73f5d6e93a6c4982edeaf413c3f938e232dcaeb4eac869746d15d16b4ad7913f65f2ef2124dd588d3c7dfe8c795486e985a09

test:
  secret_key_base: 954da2daaa9fd8594a2afb9b9eab5811c3f2807a073935f932c81dbb87bc1cbd4e0cef076802aa20f74e074ed308377080c102f2cb71a7bab198db4c21154b03

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
